### PR TITLE
Update Twitter name

### PR DESCRIPTION
**Pull request by PunKeel**
Follow the guideline: use ASCII chr when possible.

cc @pborreli

### CODE REVIEW

**Comment by pborreli** [comment]
link to the guideline ?

**Comment by PunKeel** [comment]
Guideline is available here : https://github.com/PunKeel/pborreli/blob/master/GUIDELINE.MD

**Comment by pborreli** [comment]
Ok now i just want to add UTF8 and Emoji in Location too

**Comment by PunKeel** [comment]
Please open a new PR, then. This one is for your name. :dart:

**Comment by pborreli** [comment]
:-1: let's keep UTF8 for his name for the sake of:
- google indexing
- adding cute emoji on some clients
- who cares about ascii anyway, vive UTF8

**Pull request closed without merging**
